/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3393D1',
          dark: '#1F6E9F',
          container: '#007bb7',
          fixed: '#cbe6ff',
          'fixed-dim': '#90cdff',
          'on-fixed': '#001e31',
          'on-fixed-variant': '#004b72',
        },
        secondary: {
          DEFAULT: '#096494',
          container: '#85c8fe',
          'on-container': '#00537e',
          fixed: '#cbe6ff',
          'fixed-dim': '#90cdff',
        },
        tertiary: {
          DEFAULT: '#006947',
          container: '#00855b',
          'on-container': '#f5fff6',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
        },
        whatsapp: '#10B981',
        'whatsapp-green': '#25D366',
        surface: {
          DEFAULT: '#FAF8FF',
          warm: '#FAF9F6',
          dim: '#d2d9f4',
          bright: '#faf8ff',
          container: '#eaedff',
          'container-low': '#f2f3ff',
          'container-high': '#e2e7ff',
          'container-highest': '#dae2fd',
          'container-lowest': '#ffffff',
          variant: '#dae2fd',
          tint: '#3393D1',
        },
        'on-surface': '#131B2E',
        'on-surface-variant': '#3F4850',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#FCFCFF',
        'on-secondary': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'on-background': '#131B2E',
        background: '#FAF8FF',
        'slate-dark': '#0F172A',
        'slate-muted': '#475569',
        'border-subtle': '#E2E8F0',
        'accent-gold': '#F59E0B',
        'outline-variant': '#BFC7D1',
        outline: '#707881',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#EEF0FF',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'margin-mobile': '1.25rem',
        'margin-desktop': '2rem',
        'section-gap': '4rem',
        'card-padding': '1.5rem',
        gutter: '1.5rem',
      },
      boxShadow: {
        card: '0 4px 20px -2px rgba(51, 147, 209, 0.08)',
        'card-hover': '0 10px 30px -4px rgba(51, 147, 209, 0.16)',
        button: '0 4px 14px 0 rgba(51, 147, 209, 0.39)',
        'whatsapp-glow': '0 4px 20px 0 rgba(16, 185, 129, 0.3)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
